### PR TITLE
fix: Recreating page 404 with a new UI

### PR DESCRIPTION
**Pull request by Kevindm14**
- Adding new UI for the 404 Page

I changed UI on the new page 404 because it could look better than it looks now with the help of @paganotoni.

I added a new file related to the 4 number on the side of the Buffalo Logo.

### CODE REVIEW

**Review by sio4 — APPROVED** [review]
even though I didn't see the output, I believe it could be better than my work! ;-)

**Comment by paganotoni** [comment]
@Kevindm14 can you add a screenshot of the 404 page? Thanks!

**Comment by paganotoni** [comment]
@sio4 I think you did a lot of leg work on setting the 404 page. This PR looks to be more of tweaking the UI.

**Comment by paganotoni** [comment]
[Offtopic] We're needing that netlify deployment configuraton. That would give us preview URL's.

**Comment by sio4** [comment]
> @sio4 I think you did a lot of leg work on setting the 404 page. This PR looks to be more of tweaking the UI.

actually, I thought "oh, I need designer friends..." during the work :-)

**Pull request merged**
